
from app.security import hash_password


DEMO_PASSWORD = "Reflex@2026"


DEMO_USERS = [
    {
        "id": "USR-001",
        "name": "J. Kamau",
        "email": "retailer@reflex.co.ke",
        "role": "retailer",
        "organization": "MetroTech Electronics",
        "password_hash": hash_password(
            DEMO_PASSWORD
        ),
    },
    {
        "id": "USR-002",
        "name": "A. Wanjala",
        "email": "dispatcher@reflex.co.ke",
        "role": "dispatcher",
        "organization": "Reflex Dispatch",
        "password_hash": hash_password(
            DEMO_PASSWORD
        ),
    },
    {
        "id": "USR-003",
        "name": "David Mwangi",
        "email": "rider@reflex.co.ke",
        "role": "rider",
        "organization": "Reflex Riders",
        "password_hash": hash_password(
            DEMO_PASSWORD
        ),
    },
]


DEMO_RIDERS = [
    {
        "id": "RDR-001",
        "name": "David Mwangi",
        "phone": "0722 118 420",
        "available": True,
        "active_deliveries": 1,
    },
    {
        "id": "RDR-002",
        "name": "Kevin Kiptoo",
        "phone": "0710 330 208",
        "available": True,
        "active_deliveries": 0,
    },
    {
        "id": "RDR-003",
        "name": "Samuel Maina",
        "phone": "0715 463 201",
        "available": False,
        "active_deliveries": 2,
    },
    {
        "id": "RDR-004",
        "name": "James Kariuki",
        "phone": "0708 772 304",
        "available": True,
        "active_deliveries": 1,
    },
]


DEMO_DELIVERIES = [
    {
        "id": "RFX-1013",
        "retailer": "City Office Supplies",
        "customer": "Faith Akinyi",
        "phone": "0720 884 311",
        "customer_phone": "0720 884 311",
        "pickup": "CBD, Nairobi",
        "destination": "Upper Hill, Nairobi",
        "item": "Document envelope",
        "delivery_notes": None,
        "rider": "David Mwangi",
        "rider_phone": "0722 118 420",
        "status": "assigned",
        "priority": "normal",
        "created_at": "26 Aug 2026, 5:12 PM",
        "updated_at": "26 Aug 2026, 5:12 PM",
        "assigned_at": "26 Aug 2026, 5:12 PM",
        "confirmation_status": "not_ready",
    },
    {
        "id": "RFX-1012",
        "retailer": "MetroTech Electronics",
        "customer": "Anne Wambui",
        "phone": "0712 450 221",
        "customer_phone": "0712 450 221",
        "pickup": "Westlands, Nairobi",
        "destination": "Kileleshwa, Nairobi",
        "item": "Laptop charger",
        "delivery_notes": None,
        "rider": None,
        "rider_phone": None,
        "status": "pending",
        "priority": "high",
        "created_at": "26 Aug 2026, 5:40 PM",
        "updated_at": "26 Aug 2026, 5:40 PM",
        "assigned_at": None,
        "confirmation_status": "not_ready",
    },
    {
        "id": "RFX-1011",
        "retailer": "AfyaPlus Pharmacy",
        "customer": "Dennis Kiprotich",
        "phone": "0728 119 804",
        "customer_phone": "0728 119 804",
        "pickup": "Ngara, Nairobi",
        "destination": "Kilimani, Nairobi",
        "item": "Prescription medicine package",
        "delivery_notes": None,
        "rider": None,
        "rider_phone": None,
        "status": "pending",
        "priority": "urgent",
        "created_at": "26 Aug 2026, 5:18 PM",
        "updated_at": "26 Aug 2026, 5:18 PM",
        "assigned_at": None,
        "confirmation_status": "not_ready",
    },
    {
        "id": "RFX-1010",
        "retailer": "BuildRight Hardware",
        "customer": "Mary Njeri",
        "phone": "0705 663 891",
        "customer_phone": "0705 663 891",
        "pickup": "Industrial Area, Nairobi",
        "destination": "South C, Nairobi",
        "item": "Electrical fittings",
        "delivery_notes": None,
        "rider": None,
        "rider_phone": None,
        "status": "pending",
        "priority": "normal",
        "created_at": "26 Aug 2026, 4:55 PM",
        "updated_at": "26 Aug 2026, 4:55 PM",
        "assigned_at": None,
        "confirmation_status": "not_ready",
    },
    {
        "id": "RFX-1009",
        "retailer": "MetroTech Electronics",
        "customer": "John Mutua",
        "phone": "0790 305 778",
        "customer_phone": "0790 305 778",
        "pickup": "CBD, Nairobi",
        "destination": "Parklands, Nairobi",
        "item": "Wireless mouse",
        "delivery_notes": None,
        "rider": "David Mwangi",
        "rider_phone": "0722 118 420",
        "status": "assigned",
        "priority": "normal",
        "created_at": "26 Aug 2026, 4:20 PM",
        "updated_at": "26 Aug 2026, 4:20 PM",
        "assigned_at": "26 Aug 2026, 4:20 PM",
        "confirmation_status": "not_ready",
    },
    {
        "id": "RFX-1008",
        "retailer": "MetroTech Electronics",
        "customer": "Grace Wanjiku",
        "phone": "0712 345 678",
        "customer_phone": "0712 345 678",
        "pickup": "Westlands, Nairobi",
        "destination": "Kilimani, Nairobi",
        "item": "HP laptop charger",
        "delivery_notes": None,
        "rider": "David Mwangi",
        "rider_phone": "0722 118 420",
        "status": "in_transit",
        "priority": "high",
        "created_at": "26 Aug 2026, 2:30 PM",
        "updated_at": "26 Aug 2026, 4:18 PM",
        "assigned_at": "26 Aug 2026, 2:40 PM",
        "confirmation_status": "not_ready",
    },
    {
        "id": "RFX-1007",
        "retailer": "MetroTech Electronics",
        "customer": "Brian Otieno",
        "phone": "0798 442 113",
        "customer_phone": "0798 442 113",
        "pickup": "CBD, Nairobi",
        "destination": "Westlands, Nairobi",
        "item": "Wireless keyboard and mouse",
        "delivery_notes": None,
        "rider": "Kevin Kiptoo",
        "rider_phone": "0710 330 208",
        "status": "picked_up",
        "priority": "normal",
        "created_at": "26 Aug 2026, 1:15 PM",
        "updated_at": "26 Aug 2026, 3:42 PM",
        "assigned_at": "26 Aug 2026, 1:30 PM",
        "confirmation_status": "not_ready",
    },
    {
        "id": "RFX-1006",
        "retailer": "AfyaPlus Pharmacy",
        "customer": "Mercy Achieng",
        "phone": "0701 728 551",
        "customer_phone": "0701 728 551",
        "pickup": "Ngara, Nairobi",
        "destination": "Lavington, Nairobi",
        "item": "Two sealed medicine packages",
        "delivery_notes": None,
        "rider": None,
        "rider_phone": None,
        "status": "pending",
        "priority": "urgent",
        "created_at": "26 Aug 2026, 11:42 AM",
        "updated_at": "26 Aug 2026, 11:42 AM",
        "assigned_at": None,
        "confirmation_status": "not_ready",
    },
    {
        "id": "RFX-1005",
        "retailer": "BuildRight Hardware",
        "customer": "Peter Kamau",
        "phone": "0724 811 640",
        "customer_phone": "0724 811 640",
        "pickup": "Industrial Area, Nairobi",
        "destination": "South B, Nairobi",
        "item": "Hardware tools",
        "delivery_notes": None,
        "rider": "Samuel Maina",
        "rider_phone": "0715 463 201",
        "status": "completed",
        "priority": "normal",
        "created_at": "26 Aug 2026, 9:25 AM",
        "updated_at": "26 Aug 2026, 12:58 PM",
        "assigned_at": "26 Aug 2026, 9:35 AM",
        "confirmation_status": "confirmed",
    },
    {
        "id": "RFX-1004",
        "retailer": "MetroTech Electronics",
        "customer": "Faith Njeri",
        "phone": "0788 902 445",
        "customer_phone": "0788 902 445",
        "pickup": "Parklands, Nairobi",
        "destination": "Parklands, Nairobi",
        "item": "Phone accessories",
        "delivery_notes": None,
        "rider": "James Kariuki",
        "rider_phone": "0708 772 304",
        "status": "delivered",
        "priority": "normal",
        "created_at": "25 Aug 2026, 4:10 PM",
        "updated_at": "25 Aug 2026, 5:55 PM",
        "assigned_at": "25 Aug 2026, 4:20 PM",
        "confirmation_status": "awaiting_confirmation",
    },
    {
        "id": "RFX-1003",
        "retailer": "MetroTech Electronics",
        "customer": "Cynthia Njeri",
        "phone": "0711 940 113",
        "customer_phone": "0711 940 113",
        "pickup": "Kilimani, Nairobi",
        "destination": "Karen, Nairobi",
        "item": "Bluetooth headphones",
        "delivery_notes": None,
        "rider": "David Mwangi",
        "rider_phone": "0722 118 420",
        "status": "completed",
        "priority": "normal",
        "created_at": "25 Aug 2026, 10:15 AM",
        "updated_at": "25 Aug 2026, 1:20 PM",
        "assigned_at": "25 Aug 2026, 10:25 AM",
        "confirmation_status": "confirmed",
    },
]


DEMO_NOTIFICATIONS = [
    {
        "id": 1,
        "title": "New delivery assigned",
        "message": (
            "Delivery RFX-1013 has been assigned "
            "to you. Pickup is at CBD, Nairobi."
        ),
        "time": "8 min ago",
        "type": "assignment",
        "read": False,
        "delivery_id": "RFX-1013",
        "user_id": "USR-003",
    },
    {
        "id": 2,
        "title": "Delivery confirmed",
        "message": (
            "The customer confirmed receipt "
            "of delivery RFX-1003."
        ),
        "time": "Yesterday, 1:22 PM",
        "type": "confirmation",
        "read": True,
        "delivery_id": "RFX-1003",
        "user_id": "USR-003",
    },
    {
        "id": 3,
        "title": "Status successfully updated",
        "message": (
            "RFX-1008 was updated to In Transit."
        ),
        "time": "Today, 4:18 PM",
        "type": "status",
        "read": True,
        "delivery_id": "RFX-1008",
        "user_id": "USR-003",
    },
    {
        "id": 4,
        "title": "Reflex rider account",
        "message": (
            "Your rider profile is active and "
            "available for delivery assignments."
        ),
        "time": "25 Aug, 8:00 AM",
        "type": "system",
        "read": True,
        "delivery_id": None,
        "user_id": "USR-003",
    },
]
